version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6
    working_directory: ~/caffeine
    steps:
      - checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: env MIX_ENV=test mix compile
      - run: mix test
      - run: env MIX_ENV=test mix coveralls.circle
      - run: mix format --check-formatted
      - run: env MIX_ENV=test mix do compile --warnings-as-errors, coveralls.json
      - run: bash <(curl -s https://codecov.io/bash)
      # - run: mix dialyzer
