version: 2
jobs:
  build:
    docker:
      - image: circleci/elixir:1.6
    working_directory: ~/caffeine
    steps:
      - checkout
      - run: mix local.rebar --force
      - run: mix local.hex --force
      - run: mix deps.get
      - run: mix test
      - run: env MIX_ENV=test mix coveralls.circle
      - restore_cache:
          keys:
            - Dialyzer PLT
      - run: mix dialyzer
      - save_cache:
          key: Dialyzer PLT
          paths: ".dialyzer"
